name: chat_package
description: Fully functional chat ui for flutter, with functionality to send
  text, voice notes,and images
version: 2.0.1
homepage: https://github.com/MOUKZ/chat_package

environment:
  sdk: 3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  provider: ^6.1.5
  record: ^6.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
